import math

# 1 Simulation Mass Unit = 1 Solar Mas
# 100 Pixels = 1 Light Year
# Mass in simulation = MASS_SCALER * Real Mass
# Length in simulation = LENGTH_SCALER * Real Length
# Time in simulation = TIME_SCALER * Real Time

SPEED_OF_LIGHT = 299792458
SECONDS_PER_DAY = 86400
DAYS_PER_YEAR = 365.2422
SOLAR_MASS = 1.988416e30
G_CONSTANT = 6.67428e-11

MASS_SACLER = 1 / SOLAR_MASS
LENGTH_SCALER = 100 / (DAYS_PER_YEAR * SECONDS_PER_DAY * SPEED_OF_LIGHT)

TIME_SCALER = math.sqrt((G_CONSTANT * LENGTH_SCALER ** 3)/(MASS_SACLER))
REAL_TIME = 1 / TIME_SCALER

print(f"""
MASS_SACLER: {MASS_SACLER}
LENGTH_SCALER: {LENGTH_SCALER}
TIME_SCALER: {TIME_SCALER}
REAL_TIME IN YEARS: {REAL_TIME / (DAYS_PER_YEAR * SECONDS_PER_DAY)}
""")
